### ISSUE TITLE
Not able to apply digital badge

### ISSUE THREAD

**Issue by Harshjaswal** [OfficeDev/microsoft-teams-apps-champion-management#128] opened 2022-10-10 08:32 UTC
Hi Team,

I am not able to apply the digital badge. Below are the screenshots:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/28647817/194825306-b512791d-1db5-4947-aa84-7774920a1380.png">
<img width="946" alt="image" src="https://user-images.githubusercontent.com/28647817/194825451-29f3239a-f7bb-4bb6-92bc-511fc50d432d.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/28647817/194825538-4facb1fd-2419-41fa-a9dd-40be4fb1b563.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/28647817/194825744-179e4503-7a05-42d3-940c-f94f9a4b3143.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/28647817/194826332-6b7d9fdb-579a-4800-be3a-a8448be736f5.png">

**Comment by v-saikirang** [comment] 2022-10-10 11:41
Hi @Harshjaswal,
Thanks for reaching out to us. 
May I know if this was working earlier and stopped working now? Can you please check with any other user too.

Please try again and share the console logs for further investigation if you still see the issue.
Thanks.

**Comment by Harshjaswal** [comment] 2022-10-11 06:46
Hi @v-saikirang,

Please find below my answers:

1. This was never working.
2.  Others are also facing the same issue.
3. All the permissions which are mentioned [here ](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/issues/10)are assigned and approved. I can't share the screenshot due to company policies.
4. Tried again, the errors in the console are same as I have shared earlier in this beginning of this thread.

**Comment by v-prigunasek** [comment] 2022-10-11 07:36
Hi @Harshjaswal ,

Can you please call the below api in the Graph Explorer and see whether it is successful?
https://graph.microsoft.com/v1.0/me/photo/$value

![image](https://user-images.githubusercontent.com/98514691/195023156-0a246423-6625-4654-bccd-3bba0efe45b4.png)

Also please check and confirm whether these 2 permissions (Sites.Manage.All , User.ReadWrite) are available under API Permissions in "SharePoint Online Client Extensibility Web Application Principal" application?

Goto  Azure Portal >> App Registrations >> Under All applications click on "SharePoint Online Client Extensibility Web Application Principal" >> API Permissions.

![image](https://user-images.githubusercontent.com/98514691/195023461-db6fdfc8-d383-4bf4-9123-cdedda271f37.png)

**Comment by Harshjaswal** [comment] 2022-10-11 08:42
Hi @v-prigunasek,

Please find my answers below:

1. The API fails in the graph explorer: 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/28647817/195042036-af7f6226-8ba0-4588-990d-967f4086b73f.png">

2. Sites.Manage.All and User.ReadWrite are available under API Permissions in "SharePoint Online Client Extensibility Web Application Principal" application.

**Comment by v-prigunasek** [comment] 2022-10-11 09:33
Thanks for checking this out, @Harshjaswal. 

We will replicate this scenario from our end and if it is something not handled properly in the code, we will get this fixed in our next release. 

Please let me know if this can be closed since you are able to apply the badges after adding profile picture.

**Comment by Harshjaswal** [comment] 2022-10-11 09:36
Sure @v-prigunasek , But if you could provide the tentative date by when the fix will be rolled out that would be very helpful.

**Comment by v-prigunasek** [comment] 2022-10-11 09:49
Hi @Harshjaswal ,

We don't have the release date as of now, but you can watch for the updates on this repo. Thanks!

**Closed** 2022-10-11 10:21 UTC
Labels: needs: attention :wave:

**Comment by v-prigunasek** [comment] 2022-10-12 04:45
Hi @Harshjaswal ,

Can you please check and confirm whether you have CDN enabled in your tenant and has */CLIENTSIDEASSETS origin in the Public CDN? Thanks!

**Comment by v-prigunasek** [comment] 2022-10-12 12:42
Thanks for confirming that, @Harshjaswal.

We were able to reproduce this issue at our end, however this issue is limited to users who don't have a profile image in the CDN enabled tenants. App is working fine for the users who already have a profile image.

As mentioned earlier, we will fix this in our next release. Thanks!

**Comment by Harshjaswal** [comment] 2022-10-17 08:45
Hi @v-prigunasek, @v-saikirang,

One question here:

The step number 11 in [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Deployment-Guide) talks about the "Sites.Manage.All" permission to the app package. Just wanted to check if this permission is only needed to create the SharePoint lists and libraries on which the app then after the dependents lists are created can we remove this permission or is it still needed for the app to function properly. If its still needed, is there any option to downgrade the permission so that that this app package has the permission to the specific SharePoint site only.

**Comment by v-saikirang** [comment] 2022-10-17 09:30
Hi @Harshjaswal,

Yes, this permission is required only to create the site and lists while setting up the app. And you can remove this permission if you are done with the set up and started using the app.
Thanks.

**Comment by Harshjaswal** [comment] 2022-10-28 10:12
Hi @v-saikirang , @v-prigunasek ,

The User.ReadWrite Permission which is needed for this app, is it delegated permission or application level permission?

**Comment by v-saikirang** [comment] 2022-10-28 11:21
Hi @Harshjaswal,

It is a delegated permission.

Thanks.
