### ISSUE TITLE
App not updating profile picture with badge

### ISSUE THREAD

**Issue by UnknownNamez** [OfficeDev/microsoft-teams-apps-champion-management#10] opened 2021-04-14 09:32 UTC
Hi,
we successfull installed the App at our tenant and everything works fine except the update profile picture function. We didn't customized anything just used the default app. All API Requests are granted!

PS: Downloading your own profilpicture works!

![ChampionPlatform_Error](https://user-images.githubusercontent.com/28800027/114688496-080ee500-9d15-11eb-90b9-16f64c977601.png)

**Comment by yhabersaat** [comment] 2021-04-19 07:14
Errors related:

clb-home-web-part_b1cbeaebdb2dfe4d2fc7493714d6d706.js:1 getPhotoBits error: SecurityError: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported

clb-home-web-part_b1cbeaebdb2dfe4d2fc7493714d6d706.js:1 _updateUserPhoto error: TypeError: Cannot set property 'lastModifiedDate' of undefined

**Comment by Smitat-msft** [comment] 2021-04-28 04:47
@yhabersaat @UnknownNamez  Thanks for being patient. Looks like a permission issue. let me repro and get a resolution to this issue.

**Comment by eshwarmsft** [comment] 2021-04-28 17:08
This issue will come when the permissions are not being inherited or approved after deploying the sharepoint package at the time of uploading from appcatalogue.
![issue10](https://user-images.githubusercontent.com/69787520/116444547-748bf700-a872-11eb-9a10-73832d2bf389.PNG)
![issue10_1](https://user-images.githubusercontent.com/69787520/116444555-75bd2400-a872-11eb-9635-4974c99c674e.PNG)
![issue10_2](https://user-images.githubusercontent.com/69787520/116444557-75bd2400-a872-11eb-9608-095e02068b47.PNG)
![issue10_3](https://user-images.githubusercontent.com/69787520/116444559-7655ba80-a872-11eb-9bbc-29dde4792c8f.PNG)

**Comment by yhabersaat** [comment] 2021-04-28 21:04
Redeployed the solution in the app catalog and approved the permissions, still not working:
![image](https://user-images.githubusercontent.com/15676985/116471566-1dd3ec80-a875-11eb-935b-7f01d9744729.png)

**Comment by eshwarmsft** [comment] 2021-04-29 04:19
Thanks for trying the fix by redeploying and approving the permissions. 

Sometimes the permissions take a little time to apply. Would you please take one more try by closing all the browsers and removing the existing profile image and try to update the profile pic from digital badge. If the issue still persists, Please provide the availability of call with screen share for better insights for us to troubleshoot if possible.

**Comment by pratikdedhia1987** [comment] 2021-05-12 20:49
@eshwarmsft - I am working with a customer who has the exact same issue. I verified the permission's for API access and they have been approved. Any idea on how do we fix the issue ? If you have time, I can setup a call with customer to troubleshoot.

**Comment by eshwarmsft** [comment] 2021-05-13 13:10
Hi @Pratikd-msft  

Thanks for the update, There is no new permissions required if the cmp package is deployed with checkbox checked as shown 
![image](https://user-images.githubusercontent.com/69787520/118130005-80eb8480-b41a-11eb-99b1-0745d2d4b708.png) and approved permissions as mentioned. Would you please try to remove the package and try to do install again with these two steps once again.
![image](https://user-images.githubusercontent.com/69787520/118130029-89dc5600-b41a-11eb-9387-29662dc0a757.png)

**Comment by Pratikd-msft** [comment] 2021-05-21 16:29
@eshwarmsft We followed the steps of redeploying again and still facing the issue. Anything logs or anything else I can check.

**Comment by eshwarmsft** [comment] 2021-05-26 13:13
@Pratikd-msft  Would you please give a try with the updated changes from  version CMP 1.0.0.0

**Comment by jeff29922** [comment] 2021-06-21 17:38
@eshwarmsft @Pratikd-msft is OOF on Paternity leave, I am backing him up and I am working with his customer on this issue.  They have updated the app with the recommended changes, this has not fixed the issue.  They are still having issues with updating the user profile with a badge.  Can you please let me know of any logs/diagnostic data that I can pull and upload to help with troubleshooting this issue.

**Comment by jeff29922** [comment] 2021-06-22 16:58
@Smitat-msft I am going to have my customer reproduce this issue with debug turned on in Edge.  I will forward you the logs to review.

**Comment by v-saikirang** [comment] 2021-07-23 08:02
Hi @UnknownNamez , @jeff29922 , @Pratikd-msft , @yhabersaat,

 Thanks for your patience! We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by samuel-weber** [comment] 2021-07-30 12:24
Hi. I created a PR (#49) fixing this problem. I had to set the crossOrigin to "Anonymous", allowing canvas handling different image-origins....

**Comment by v-saikirang** [comment] 2021-07-30 12:35
Hi @samuel-weber,

We have already implemented this and it will be part of our next release. Thanks for sharing this.

Thanks.

**Comment by JoshLeporati** [comment] 2021-08-18 14:12
As mentioned this will be addressed in an upcoming release, will update here when the release is available!

**Comment by hkuu** [comment] 2021-10-04 12:15
Was this already fixed? We are facing similar issues with the badge and it was mentioned earlier that "will update here when the release is available"?

**Comment by SjoerdV** [comment] 2021-11-04 12:23
Same issue here while using a cloud account as a Champion (so no AD writeback stuff is involved)
solution version: 1.3.0.0
![image](https://user-images.githubusercontent.com/13275320/140312558-0b853fd8-13c5-4890-8c5c-cff37451c469.png)

**Comment by v-saikirang** [comment] 2021-11-16 07:22
Hi @rajdeep1510,

If you are fine, we can work on this troubleshooting offline. We can try out few fixes in your tenant. Can you please share your email ID and we can take this forward.
Thanks.

**Comment by rajdeep1510** [comment] 2021-11-16 16:55
sure @v-saikirang, rajdeep1510@rediff.com

**Comment by v-saikirang** [comment] 2021-11-22 04:02
Hi @SjoerdV,

Thanks for your patience. Please let me know if you are fine with troubleshooting this offline in your tenant. If you can share your Email we can work together on this.
Thanks.

**Comment by v-saikirang** [comment] 2021-11-30 11:49
Hi @hkuu,

Please let us know if you want to try trouble shoot this in your tenant. If you can share your email we can take this forward and i can share further instructions.

Thanks.

**Comment by hkuu** [comment] 2021-12-03 07:15
> Hi @hkuu,
> 
> Please let us know if you want to try trouble shoot this in your tenant. If you can share your email we can take this forward and i can share further instructions.
> 
> Thanks.

Hi, could you share ideas for fixes here instead as it seems that our environment is not the only one where this badge is not working. 

@v-saikirang

**Comment by Porkai-Pandian** [comment] 2022-08-03 18:18
Closing out this issue, if the issue is still happening, please open a new one.

**Closed by Porkai-Pandian** 2022-08-03 18:18 UTC
Labels: enhancement
