### ISSUE TITLE
Upgrade from 2.3 -> 2.4, Config List Error

### ISSUE THREAD

**Issue by opinionpivot** [OfficeDev/microsoft-teams-apps-champion-management#148] opened 2023-01-26 18:49 UTC
Hello,

I have the following error screen after upgrade to 2.4 from 2.3.
![image](https://user-images.githubusercontent.com/123667981/214922297-f324f673-4fcd-4403-87b4-86c8511a5e14.png)

Here is the Config List on the backend.
![image](https://user-images.githubusercontent.com/123667981/214922378-b92cf428-2f1b-41b9-8d75-d12e1bd8f742.png)

I don't know if this is relevant, but when following the upgrade instructions, I get this error when adding it to Teams. However, the Champions app does show 2.4 within Teams. 
![image](https://user-images.githubusercontent.com/123667981/214923503-d204c718-fe21-42cd-b882-e34c8fc7ef2f.png)

**Comment by v-saikirang** [comment] 2023-01-27 05:48
Hi @opinionpivot,

Thanks for reaching out to us.

For some reason the default values in the config list didn't get updated. Can you please adding these exact entries to the list and see if it works. You can click on "Edit in grid view" on top of the list add them quickly.

![image](https://user-images.githubusercontent.com/87538202/215018348-18dc4703-9869-404b-9fd5-6183f50a0b74.png)

Thanks.

**Comment by opinionpivot** [comment] 2023-01-27 13:02
@v-saikirang That worked for me! Thank you.

I have an additional question, please.

I can't tell if the upgrade was successful due to some mixed version messaging. I also don't how to test any of the new features with 2.4 to verify. Can you help me figure out which version our tenant is currently using?

 App info says 2.4, as well as screenshot is my previous post in SharePoint admin center:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/123667981/215093162-20311711-6000-480a-9495-c364f1cf3eed.png)

Teams admin center, app store, and app about all say 2.3.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/123667981/215093280-7df8eebd-e5de-4235-9e90-5cff6cd49d03.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/123667981/215093292-6bf0adf9-73c6-496c-8c78-fda9fe5b85c7.png)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/123667981/215093302-9749b1b6-daba-4bf1-afec-da604294b4e7.png)

**Comment by v-saikirang** [comment] 2023-01-27 13:27
Hi @opinionpivot,

It looks like the app didn't sync to Teams due to which the app is still showing the version as 2.3. But the app is already consuming the package from 2.4. This is confirmed from "About CMP" info icon. So You can try couple things:

1) Delete the package from App catalog and upload the 2.4 package again and "Add to Teams". If this fails again you can try the option 2
2) Delete the app from Admin center and then "Add to Teams". No other steps are required. Please note that this will delete the app and then add it again. So you might have to re add this app if you already have it added as a tab to any teams or if some one pinned it. 

Please let me know if this worked.

Thanks.

**Comment by opinionpivot** [comment] 2023-01-27 14:01
Hi @v-saikirang 

#1 didn't change anything
#2 worked! 

Thank you!!!

**Comment by v-saikirang** [comment] 2023-01-27 14:05
Thanks for the confirmation. I am closing the ticket. Please create a new ticket if you see any other issues.

**Closed** 2023-01-30 04:27 UTC
Labels: status: fixed
